-- MySQL Script generated by MySQL Workbench
-- Mon Jun 26 16:51:58 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Local`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Local` (
  `idLocal` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLocal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `idLocal` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_Cliente_Cidade1_idx` (`idLocal` ASC),
  CONSTRAINT `fk_Cliente_Cidade1`
    FOREIGN KEY (`idLocal`)
    REFERENCES `mydb`.`Local` (`idLocal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProCid`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProCid` (
  `idProCid` INT NOT NULL,
  PRIMARY KEY (`idProCid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proimg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proimg` (
  `idProimg` INT NOT NULL,
  PRIMARY KEY (`idProimg`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProCid_has_Proimg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProCid_has_Proimg` (
  `ProCid_idProCid` INT NOT NULL,
  `Proimg_idProimg` INT NOT NULL,
  PRIMARY KEY (`ProCid_idProCid`, `Proimg_idProimg`),
  INDEX `fk_ProCid_has_Proimg_Proimg1_idx` (`Proimg_idProimg` ASC),
  INDEX `fk_ProCid_has_Proimg_ProCid_idx` (`ProCid_idProCid` ASC),
  CONSTRAINT `fk_ProCid_has_Proimg_ProCid`
    FOREIGN KEY (`ProCid_idProCid`)
    REFERENCES `mydb`.`ProCid` (`idProCid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProCid_has_Proimg_Proimg1`
    FOREIGN KEY (`Proimg_idProimg`)
    REFERENCES `mydb`.`Proimg` (`idProimg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Propaganda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Propaganda` (
  `idPropaganda` INT NOT NULL AUTO_INCREMENT,
  `idLocal` INT NOT NULL,
  `imagemrosto` VARCHAR(45) NULL,
  `link` VARCHAR(45) NULL,
  PRIMARY KEY (`idPropaganda`),
  INDEX `fk_Propaganda_Cidade1_idx` (`idLocal` ASC),
  CONSTRAINT `fk_Propaganda_Cidade1`
    FOREIGN KEY (`idLocal`)
    REFERENCES `mydb`.`Local` (`idLocal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Imagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Imagem` (
  `idImagem` INT NOT NULL AUTO_INCREMENT,
  `idLocal` INT NOT NULL,
  `descricao` VARCHAR(150) NULL,
  `seguranca` INT(1) NOT NULL,
  `transporte` INT(1) NOT NULL,
  `lazer` INT(1) NOT NULL,
  `Imagem` BLOB NOT NULL,
  PRIMARY KEY (`idImagem`),
  INDEX `fk_Imagem_Cidade1_idx` (`idLocal` ASC),
  CONSTRAINT `fk_Imagem_Cidade1`
    FOREIGN KEY (`idLocal`)
    REFERENCES `mydb`.`Local` (`idLocal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
